# Generated by Django 3.1 on 2022-12-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product-gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
